from manage.ColorsManager import *

DEBUG_ACTIVE = False

APP_VERSION = "1.1.07"
APP_NAME = "PyDashboard  " + APP_VERSION

NUMERO_RIGHE = 30
OK = 'OK'
KO = 'KO'
SKIP = '-'
COLUMN_WIDTH_DESC = '700px'
COLUMN_WIDTH_THRESHOLD = '30px'

HREF_PAGE_COMMON = '/page_common'
HREF_PAGE_SINGLE = '/page_single'
HREF_PAGE_TEST = '/page_test'
HREF_PAGE_SEARCH = '/page_search'

ALIGN_CENTER = 'center'
ALIGN_LEFT = 'left'
ALIGN_RIGHT = 'right'
ALIGN_TOP = 'top'
ALIGN_BOTTOM = 'bottom'
ALIGN_TOP_LEFT = 'top-left'

UNDERLINE = 'underline'

CURSOR_HAND = 'pointer'

FONT_BOLD = 'Bold'
FONT_ITALIC = 'Italic'
FONT_CALIBRI = 'Calibri'

TEXT_SMALL_SIZE = 13
TEXT_MEDIUM_SIZE = 16
TEXT_LARGE_SIZE = 21

OVERFLOW_ELLIPSIS = 'ellipsis'
OVERFLOW_HIDDEN = 'hidden'

MARGIN = '2vw'

BORDER_WIDTH = 1
BORDER_STYLE = 'solid'
BORDER_RADIUS = 10

TABLE_BORDER = '2px solid #7A7A7A'
TABLE_DATA_SIZE = 16
TABLE_CELL_FAKE_WIDTH = 150  # serve solo ad avere le colonne della stessa dimensione

HEADER_BORDER = TABLE_BORDER
HEADER_BACKGROUND = COLOR_GREY_DARK
HEADER_COLOR = COLOR_GREY
HEADER_FONT = FONT_CALIBRI
HEADER_FONT_SIZE = TEXT_MEDIUM_SIZE
HEADER_TEXT_ALIGN = ALIGN_CENTER
HEADER_TEXT_OVERFLOW = OVERFLOW_ELLIPSIS

INLINE = 'inline-block'
